from django.urls import path
from . import views
from .views import procesar_orden

urlpatterns = [
    path('paris/', views.paris_orders, name='paris_orders'),
    path('ripley/', views.ripley_orders, name='ripley_orders'),
    path('falabella/', views.falabella_orders, name='falabella_orders'),
    path('mercadolibre/', views.mercadolibre_orders, name='mercadolibre_orders'),
    path('ripley/order/<str:order_id>/', views.ripley_order_detail, name='ripley_order_detail'),
    path('falabella/order/<str:order_id>/', views.falabella_order_detail, name='falabella_order_detail'),
    path('mercadolibre/order/<str:order_id>/', views.mercadolibre_order_detail, name='mercadolibre_order_detail'),
    path('scanning/', views.order_scanning, name='order_scanning'),
    path('print-multiple-boletas/', views.print_multiple_boletas, name='print_multiple_boletas'),
    path('print-picking/', views.print_picking, name='print_picking'),
    path('print-packing/', views.print_packing, name='print_packing'),
    path('paris/order/<str:order_id>/', views.paris_order_detail, name='paris_order_detail'),
    path('unir-boletas/', views.unir_boletas, name='unir_boletas'),
    path('ripley/print-picking/', views.print_ripley_picking, name='print_ripley_picking'),
    path('ripley/print-packing/', views.print_ripley_packing, name='print_ripley_packing'),
    path('ripley/mark-orders-printed/', views.mark_ripley_orders_printed, name='mark_ripley_orders_printed'),
    path('ripley/mark-boletas-printed/', views.mark_ripley_boletas_printed, name='mark_ripley_boletas_printed'),
    path('marketplace/falabella/orders/', views.falabella_orders, name='falabella_orders'),
    path('marketplace/falabella/orders/print-picking/', views.print_falabella_picking, name='print_falabella_picking'),
    path('marketplace/falabella/orders/print-packing/', views.print_falabella_packing, name='print_falabella_packing'),
    path('falabella/mark-orders-printed/', views.mark_falabella_orders_printed, name='mark_falabella_orders_printed'),
    path('falabella/mark-boletas-printed/', views.mark_falabella_boletas_printed, name='mark_falabella_boletas_printed'),
    path('mercadolibre/orders/<str:order_id>/', views.mercadolibre_order_detail, name='mercadolibre_order_detail'),
    path('mercadolibre/picking/', views.print_mercadolibre_picking, name='print_mercadolibre_picking'),
    path('mercadolibre/packing/', views.print_mercadolibre_packing, name='print_mercadolibre_packing'),
    path('mercadolibre/mark-orders-printed/', views.mark_mercadolibre_orders_printed, name='mark_mercadolibre_orders_printed'),
    path('mercadolibre/mark-boletas-printed/', views.mark_mercadolibre_boletas_printed, name='mark_mercadolibre_boletas_printed'),
    path('scan-order/', views.scan_order, name='scan_order'),
    path('procesar-orden/', procesar_orden, name='procesar_orden'),
    path('mark-orders-printed/', views.mark_orders_printed, name='mark_orders_printed'),
    path('mark-boletas-printed/', views.mark_boletas_printed, name='mark_boletas_printed'),
    path('paris/orders/', views.paris_orders, name='paris_orders'),
    path('paris/orders/<str:order_number>/', views.paris_order_detail, name='paris_order_detail'),
    path('paris/print-picking/', views.print_paris_picking, name='print_paris_picking'),
    path('paris/print-packing/', views.print_paris_packing, name='print_paris_packing'),
    path('paris/mark-orders-printed/', views.mark_paris_orders_printed, name='mark_paris_orders_printed'),
    path('paris/mark-boletas-printed/', views.mark_paris_boletas_printed, name='mark_paris_boletas_printed'),
    path('paris/sales-analysis/', views.paris_sales_analysis, name='paris_sales_analysis'),
    path('paris/exportar-excel/', views.exportar_paris_orders_excel, name='exportar_paris_orders_excel'),
    path('ripley/sales-analysis/', views.ripley_sales_analysis, name='ripley_sales_analysis'),
    path('ripley/exportar-excel/', views.exportar_ripley_orders_excel, name='exportar_ripley_orders_excel'),
    path('mercadolibre/sales-analysis/', views.mercadolibre_sales_analysis, name='mercadolibre_sales_analysis'),
    path('mercadolibre/exportar-excel/', views.exportar_mercadolibre_orders_excel, name='exportar_mercadolibre_orders_excel'),
] 